apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
