apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_img
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: phpmyadmin-port
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "pgrep nginx && pgrep telegraf && pgrep php-fpm"
          periodSeconds: 10
          initialDelaySeconds: 30
